### ISSUE TITLE
Empty line in output

### ISSUE THREAD

**Issue by wezm** [wr7/refold#1]
First up thanks for this tool, it's exactly what I was looking for.

I have what appears to be a minor edge case. With the following input (note empty last line/newline after "yet."):

```
        // The glyphs are already in this order by the time they reach the Myanmar shaping
        // code in Harfbuzz. I haven't been able to work out where and why this is
        // happening yet.

```

`refold -w 100` produces this output:

```
        // The glyphs are already in this order by the time they reach the Myanmar shaping code in
        // Harfbuzz. I haven't been able to work out where and why this is happening yet.
        //
```

My expectation is that the last line would be absent. Note that this _is_ the case if I don't select the blank last line/the last line doesn't end with `\n`.

**Comment by wr7** [comment]
First of all, I'm glad that my tool is of use to someone else! And thanks for the bug report!

Based off of your description, I think that you are sending the following to `refold` (with line breaks visualized):
```
        // The glyphs are already in this order by the time they reach the Myanmar shaping\n
        // code in Harfbuzz. I haven't been able to work out where and why this is\n
        // happening yet.\n\n
```

Notice that there are two trailing line breaks at the end.

The prefix-only line that `refold` outputs at the end is intentional behavior. Essentially, `refold` "propagates" prefixes to the lines below it, and `refold` interprets the two trailing line breaks as a single empty line.

However, I will change this behavior because, as you pointed out, it is fairly unexpected. I don't have time for that tonight, so I'll probably finish that some time tomorrow.

**Comment by wezm** [comment]
Yes I think you're right regarding the two new lines. The following reproduces it:

```sh
echo -n "        // The glyphs are already in this order by the time they reach the Myanmar shaping\n        // code in Harfbuzz. I haven't been able to work out where and why this is\n        // happening yet.\n\n" | refold
```

The case that actually triggered this was a [custom task](https://zed.dev/docs/tasks) in the [Zed editor](https://zed.dev/) where I thing I have less control over the newline content:

```json
  {
    "label": "Rewrap text",
    "command": "refold -w 100 <<<\"$ZED_SELECTED_TEXT\""
  }
```

For whatever reason an extra newline appears as part of `$ZED_SELECTED_TEXT`:

<img width="997" alt="Screenshot from 2024-09-21 13-55-44" src="https://github.com/user-attachments/assets/908c5e04-bf10-47bc-a8f4-6ed47496773c">

You can see above I only selected one line but the blank line is produced by `refold`, which isn't really its fault but I don't think I can stop Zed adding the extra `\n`.

**Comment by wr7** [comment]
> You can see above I only selected one line but the blank line is produced by `refold`, which isn't really its fault but I don't think I can stop Zed adding the extra `\n`.

After doing some testing, the extra `\n` is, weirdly enough, added by the bash/zsh `<<<` operator. If you replace your task with the following, it should work how you expect it to:
```
  {
    "label": "Rewrap text",
    "command": "printf %s \"$ZED_SELECTED_TEXT\" | refold -w 100"
  }
```
However, I'm still going to change `refold` so that it works as expected with either command. As far as I know, the `<<<` is fairly common, so `refold` shouldn't suddenly start acting weird when someone uses it.

**Comment by wr7** [comment]
I've fixed the issue. I'll probably bump the version number and upload it to crates.io later today, so if you're using `cargo install`, you should be able to get this change at that point.

**Comment by wezm** [comment]
Awesome, thanks!
